import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Inventory } from '../../entities/inventory.entity';
import { InventoryCategory } from '../../enums/inventory-category.enum';
import { InventoryStatus } from '../../enums/inventory-status.enum';

@Injectable()
export class InventorySeeder {
  constructor(
    @InjectRepository(Inventory)
    private inventoryRepository: Repository<Inventory>,
  ) {}

  async seed() {
    const inventoryItems = [
      // ==================== LINENS - Sufficient Stock ====================
      {
        name: 'Sábanas - Algodón Blanco King',
        category: InventoryCategory.LINENS,
        currentStock: 150,
        minimumStock: 30,
        maximumStock: 200,
        unit: 'pieces',
        unitCost: 35.0,
        supplier: 'Proveedores de Lencería Premium',
        location: 'Almacén A - Sección 1',
        status: InventoryStatus.AVAILABLE,
      },
      {
        name: 'Sábanas - Algodón Blanco Queen',
        category: InventoryCategory.LINENS,
        currentStock: 180,
        minimumStock: 40,
        maximumStock: 250,
        unit: 'pieces',
        unitCost: 28.5,
        supplier: 'Proveedores de Lencería Premium',
        location: 'Almacén A - Sección 1',
        status: InventoryStatus.AVAILABLE,
      },
      {
        name: 'Toallas de Baño - Premium Grande',
        category: InventoryCategory.LINENS,
        currentStock: 120,
        minimumStock: 25,
        maximumStock: 180,
        unit: 'pieces',
        unitCost: 22.75,
        supplier: 'Proveedores de Lencería Premium',
        location: 'Almacén A - Sección 2',
        status: InventoryStatus.AVAILABLE,
      },
      {
        name: 'Toallas de Mano',
        category: InventoryCategory.LINENS,
        currentStock: 200,
        minimumStock: 50,
        maximumStock: 300,
        unit: 'pieces',
        unitCost: 8.5,
        supplier: 'Proveedores de Lencería Premium',
        location: 'Almacén A - Sección 2',
        status: InventoryStatus.AVAILABLE,
      },
      {
        name: 'Fundas de Almohada',
        category: InventoryCategory.LINENS,
        currentStock: 250,
        minimumStock: 60,
        maximumStock: 350,
        unit: 'pieces',
        unitCost: 6.5,
        supplier: 'Proveedores de Lencería Premium',
        location: 'Almacén A - Sección 1',
        status: InventoryStatus.AVAILABLE,
      },
      // Linens - Low Stock
      {
        name: 'Edredones - Plumón Premium',
        category: InventoryCategory.LINENS,
        currentStock: 18,
        minimumStock: 15,
        maximumStock: 50,
        unit: 'pieces',
        unitCost: 85.0,
        supplier: 'Proveedores de Lencería Premium',
        location: 'Almacén A - Sección 3',
        status: InventoryStatus.LOW_STOCK,
      },
      {
        name: 'Protectores de Colchón',
        category: InventoryCategory.LINENS,
        currentStock: 12,
        minimumStock: 10,
        maximumStock: 40,
        unit: 'pieces',
        unitCost: 18.0,
        supplier: 'Proveedores de Lencería Premium',
        location: 'Almacén A - Sección 3',
        status: InventoryStatus.LOW_STOCK,
      },

      // ==================== AMENITIES - Good Stock ====================
      {
        name: 'Champú Premium 50ml',
        category: InventoryCategory.AMENITIES,
        currentStock: 800,
        minimumStock: 150,
        maximumStock: 1200,
        unit: 'bottles',
        unitCost: 2.75,
        supplier: 'Amenidades Hoteleras Deluxe',
        location: 'Almacén B - Estante 1',
        status: InventoryStatus.AVAILABLE,
      },
      {
        name: 'Acondicionador Premium 50ml',
        category: InventoryCategory.AMENITIES,
        currentStock: 750,
        minimumStock: 150,
        maximumStock: 1200,
        unit: 'bottles',
        unitCost: 2.75,
        supplier: 'Amenidades Hoteleras Deluxe',
        location: 'Almacén B - Estante 1',
        status: InventoryStatus.AVAILABLE,
      },
      {
        name: 'Gel de Ducha 50ml',
        category: InventoryCategory.AMENITIES,
        currentStock: 900,
        minimumStock: 180,
        maximumStock: 1500,
        unit: 'bottles',
        unitCost: 2.5,
        supplier: 'Amenidades Hoteleras Deluxe',
        location: 'Almacén B - Estante 1',
        status: InventoryStatus.AVAILABLE,
      },
      {
        name: 'Jabones en Barra - Lavanda',
        category: InventoryCategory.AMENITIES,
        currentStock: 600,
        minimumStock: 120,
        maximumStock: 800,
        unit: 'bars',
        unitCost: 1.85,
        supplier: 'Amenidades Hoteleras Deluxe',
        location: 'Almacén B - Estante 2',
        status: InventoryStatus.AVAILABLE,
      },
      {
        name: 'Kits de Costura',
        category: InventoryCategory.AMENITIES,
        currentStock: 350,
        minimumStock: 80,
        maximumStock: 500,
        unit: 'pieces',
        unitCost: 1.25,
        supplier: 'Amenidades Hoteleras Deluxe',
        location: 'Almacén B - Estante 3',
        status: InventoryStatus.AVAILABLE,
      },
      {
        name: 'Cepillos de Dientes con Pasta',
        category: InventoryCategory.AMENITIES,
        currentStock: 400,
        minimumStock: 100,
        maximumStock: 600,
        unit: 'pieces',
        unitCost: 0.95,
        supplier: 'Amenidades Hoteleras Deluxe',
        location: 'Almacén B - Estante 3',
        status: InventoryStatus.AVAILABLE,
      },
      // Amenities - Low Stock
      {
        name: 'Crema Corporal 30ml',
        category: InventoryCategory.AMENITIES,
        currentStock: 85,
        minimumStock: 80,
        maximumStock: 400,
        unit: 'bottles',
        unitCost: 3.25,
        supplier: 'Amenidades Hoteleras Deluxe',
        location: 'Almacén B - Estante 2',
        status: InventoryStatus.LOW_STOCK,
      },

      // ==================== CLEANING_SUPPLIES ====================
      {
        name: 'Limpiador Multiusos Industrial',
        category: InventoryCategory.CLEANING_SUPPLIES,
        currentStock: 45,
        minimumStock: 20,
        maximumStock: 80,
        unit: 'bottles',
        unitCost: 12.5,
        supplier: 'Suministros LimpiezaPro',
        location: 'Almacén C - Zona 1',
        status: InventoryStatus.AVAILABLE,
      },
      {
        name: 'Desinfectante para Baños',
        category: InventoryCategory.CLEANING_SUPPLIES,
        currentStock: 38,
        minimumStock: 15,
        maximumStock: 70,
        unit: 'bottles',
        unitCost: 9.75,
        supplier: 'Suministros LimpiezaPro',
        location: 'Almacén C - Zona 1',
        status: InventoryStatus.AVAILABLE,
      },
      {
        name: 'Limpiavidrios Profesional',
        category: InventoryCategory.CLEANING_SUPPLIES,
        currentStock: 28,
        minimumStock: 12,
        maximumStock: 50,
        unit: 'bottles',
        unitCost: 7.25,
        supplier: 'Suministros LimpiezaPro',
        location: 'Almacén C - Zona 1',
        status: InventoryStatus.AVAILABLE,
      },
      {
        name: 'Bolsas para Aspiradora Industrial',
        category: InventoryCategory.CLEANING_SUPPLIES,
        currentStock: 22,
        minimumStock: 10,
        maximumStock: 60,
        unit: 'pieces',
        unitCost: 5.5,
        supplier: 'Suministros LimpiezaPro',
        location: 'Almacén C - Zona 2',
        status: InventoryStatus.AVAILABLE,
      },
      // Cleaning Supplies - Low Stock
      {
        name: 'Trapeadores Industriales',
        category: InventoryCategory.CLEANING_SUPPLIES,
        currentStock: 8,
        minimumStock: 8,
        maximumStock: 25,
        unit: 'pieces',
        unitCost: 15.0,
        supplier: 'Suministros LimpiezaPro',
        location: 'Almacén C - Zona 2',
        status: InventoryStatus.LOW_STOCK,
      },
      {
        name: 'Guantes de Limpieza (Cajas)',
        category: InventoryCategory.CLEANING_SUPPLIES,
        currentStock: 6,
        minimumStock: 5,
        maximumStock: 20,
        unit: 'boxes',
        unitCost: 12.0,
        supplier: 'Suministros LimpiezaPro',
        location: 'Almacén C - Zona 3',
        status: InventoryStatus.LOW_STOCK,
      },
      {
        name: 'Escobas Industriales',
        category: InventoryCategory.CLEANING_SUPPLIES,
        currentStock: 4,
        minimumStock: 4,
        maximumStock: 15,
        unit: 'pieces',
        unitCost: 18.0,
        supplier: 'Suministros LimpiezaPro',
        location: 'Almacén C - Zona 2',
        status: InventoryStatus.LOW_STOCK,
      },

      // ==================== ELECTRONICS - Varied Stock ====================
      {
        name: 'Control Remoto TV Universal',
        category: InventoryCategory.ELECTRONICS,
        currentStock: 25,
        minimumStock: 8,
        maximumStock: 40,
        unit: 'pieces',
        unitCost: 18.5,
        supplier: 'Electrónicos Hoteleros SA',
        location: 'Almacén D - Rack 1',
        status: InventoryStatus.AVAILABLE,
      },
      {
        name: 'Secadores de Pelo Profesionales',
        category: InventoryCategory.ELECTRONICS,
        currentStock: 15,
        minimumStock: 5,
        maximumStock: 30,
        unit: 'pieces',
        unitCost: 45.0,
        supplier: 'Electrónicos Hoteleros SA',
        location: 'Almacén D - Rack 2',
        status: InventoryStatus.AVAILABLE,
      },
      {
        name: 'Teléfonos de Habitación',
        category: InventoryCategory.ELECTRONICS,
        currentStock: 12,
        minimumStock: 4,
        maximumStock: 20,
        unit: 'pieces',
        unitCost: 65.0,
        supplier: 'Electrónicos Hoteleros SA',
        location: 'Almacén D - Rack 1',
        status: InventoryStatus.AVAILABLE,
      },
      // Electronics - Low Stock
      {
        name: 'Lámparas de Mesa LED',
        category: InventoryCategory.ELECTRONICS,
        currentStock: 5,
        minimumStock: 5,
        maximumStock: 25,
        unit: 'pieces',
        unitCost: 32.0,
        supplier: 'Electrónicos Hoteleros SA',
        location: 'Almacén D - Rack 3',
        status: InventoryStatus.LOW_STOCK,
      },
      {
        name: 'Adaptadores de Corriente Universal',
        category: InventoryCategory.ELECTRONICS,
        currentStock: 3,
        minimumStock: 3,
        maximumStock: 15,
        unit: 'pieces',
        unitCost: 12.5,
        supplier: 'Electrónicos Hoteleros SA',
        location: 'Almacén D - Rack 2',
        status: InventoryStatus.LOW_STOCK,
      },
      {
        name: 'Relojes Despertadores Digitales',
        category: InventoryCategory.ELECTRONICS,
        currentStock: 2,
        minimumStock: 2,
        maximumStock: 20,
        unit: 'pieces',
        unitCost: 22.0,
        supplier: 'Electrónicos Hoteleros SA',
        location: 'Almacén D - Rack 1',
        status: InventoryStatus.LOW_STOCK,
      },
    ];

    for (const itemData of inventoryItems) {
      const existingItem = await this.inventoryRepository.findOne({
        where: { name: itemData.name },
      });

      if (!existingItem) {
        await this.inventoryRepository.save(itemData);
      }
    }
  }
}
