import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Reservation } from '../../entities/reservation.entity';
import { Guest } from '../../entities/guest.entity';
import { Room } from '../../../rooms/entities/room.entity';
import { User } from '../../../auth/entities/user.entity';
import { ReservationStatus } from '../../enums/reservation-status.enum';
import { BookingChannel } from '../../enums/booking-channel.enum';

@Injectable()
export class ReservationsSeeder {
  constructor(
    @InjectRepository(Reservation)
    private reservationRepository: Repository<Reservation>,
    @InjectRepository(Guest)
    private guestRepository: Repository<Guest>,
    @InjectRepository(Room)
    private roomRepository: Repository<Room>,
    @InjectRepository(User)
    private userRepository: Repository<User>,
  ) {}

  async seed() {
    const rooms = await this.roomRepository.find();
    const guests = await this.guestRepository.find();
    const customerUser = await this.userRepository.findOne({
      where: { email: 'cliente@hotelier.com' },
    });

    if (rooms.length === 0 || guests.length === 0) {
      return;
    }

    console.log(`📊 Creating predefined reservations...`);

    const now = new Date();
    const today = new Date(now);
    today.setHours(14, 0, 0, 0); // Check-in time usually 2 PM
    const todayCheckout = new Date(now);
    todayCheckout.setHours(11, 0, 0, 0); // Check-out time usually 11 AM
    const tomorrow = new Date(now);
    tomorrow.setDate(tomorrow.getDate() + 1);
    const nextWeek = new Date(now);
    nextWeek.setDate(nextWeek.getDate() + 7);
    const yesterday = new Date(now);
    yesterday.setDate(yesterday.getDate() - 1);
    const twoDaysAgo = new Date(now);
    twoDaysAgo.setDate(twoDaysAgo.getDate() - 2);
    const threeDaysAgo = new Date(now);
    threeDaysAgo.setDate(threeDaysAgo.getDate() - 3);
    const oneWeekAgo = new Date(now);
    oneWeekAgo.setDate(oneWeekAgo.getDate() - 7);
    const twoWeeksAgo = new Date(now);
    twoWeeksAgo.setDate(twoWeeksAgo.getDate() - 14);
    const oneMonthAgo = new Date(now);
    oneMonthAgo.setMonth(oneMonthAgo.getMonth() - 1);
    const twoMonthsAgo = new Date(now);
    twoMonthsAgo.setMonth(twoMonthsAgo.getMonth() - 2);
    const threeMonthsAgo = new Date(now);
    threeMonthsAgo.setMonth(threeMonthsAgo.getMonth() - 3);

    // Helper function to create a date
    const createDate = (year: number, month: number, day: number) => {
      return new Date(year, month - 1, day, 14, 0, 0);
    };

    const reservations = [
      // Current reservations - Ready for check-in today
      {
        guestName: guests[0].name,
        guestEmail: guests[0].email,
        guestPhone: guests[0].phone,
        checkInDate: today,
        checkOutDate: new Date(today.getTime() + 3 * 24 * 60 * 60 * 1000),
        nights: 3,
        guests: 2,
        totalAmount: 945000.0,
        status: ReservationStatus.CONFIRMED,
        channel: BookingChannel.DIRECT,
        notes: 'Anniversary celebration - Ready for check-in',
        roomId: rooms[0].id,
        guestId: guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: guests[1]?.name || 'María García',
        guestEmail: guests[1]?.email || 'maria.garcia@email.com',
        guestPhone: guests[1]?.phone || '+57 300 123 4567',
        checkInDate: today,
        checkOutDate: new Date(today.getTime() + 2 * 24 * 60 * 60 * 1000),
        nights: 2,
        guests: 1,
        totalAmount: 630000.0,
        status: ReservationStatus.CONFIRMED,
        channel: BookingChannel.BOOKING_COM,
        notes: 'Business traveler - Arriving this afternoon',
        roomId: rooms[1]?.id || rooms[0].id,
        guestId: guests[1]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: guests[2]?.name || 'Carlos Rodríguez',
        guestEmail: guests[2]?.email || 'carlos.rodriguez@email.com',
        guestPhone: guests[2]?.phone || '+57 301 987 6543',
        checkInDate: yesterday,
        checkOutDate: tomorrow,
        nights: 2,
        guests: 3,
        totalAmount: 1260000.0,
        status: ReservationStatus.CHECKED_IN,
        channel: BookingChannel.EXPEDIA,
        notes: 'Family vacation - Already checked in',
        roomId: rooms[2]?.id || rooms[0].id,
        guestId: guests[2]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: guests[3]?.name || 'Ana López',
        guestEmail: guests[3]?.email || 'ana.lopez@email.com',
        guestPhone: guests[3]?.phone || '+57 302 456 7890',
        checkInDate: twoDaysAgo,
        checkOutDate: todayCheckout,
        nights: 2,
        guests: 2,
        totalAmount: 630000.0,
        status: ReservationStatus.CHECKED_IN,
        channel: BookingChannel.DIRECT,
        notes: 'Business conference - Checking out today',
        roomId: rooms[3]?.id || rooms[0].id,
        guestId: guests[3]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: guests[4]?.name || 'Pedro Martínez',
        guestEmail: guests[4]?.email || 'pedro.martinez@email.com',
        guestPhone: guests[4]?.phone || '+57 304 567 8901',
        checkInDate: threeDaysAgo,
        checkOutDate: todayCheckout,
        nights: 3,
        guests: 1,
        totalAmount: 1890000.0,
        status: ReservationStatus.CHECKED_IN,
        channel: BookingChannel.BOOKING_COM,
        notes: 'Extended weekend stay - Checking out this morning',
        roomId: rooms[4]?.id || rooms[0].id,
        guestId: guests[4]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // Future reservations
      {
        guestName: 'Roberto Silva',
        guestEmail: 'roberto.silva@email.com',
        guestPhone: '+57 305 789 0123',
        checkInDate: nextWeek,
        checkOutDate: new Date(nextWeek.getTime() + 5 * 24 * 60 * 60 * 1000),
        nights: 5,
        guests: 1,
        totalAmount: 1575000.0,
        status: ReservationStatus.PENDING,
        channel: BookingChannel.BOOKING_COM,
        notes: 'VIP guest - special attention required',
        roomId: rooms[5]?.id || rooms[0].id,
        guestId: guests[5]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Lucia Fernández',
        guestEmail: 'lucia.fernandez@email.com',
        guestPhone: '+57 306 234 5678',
        checkInDate: tomorrow,
        checkOutDate: new Date(tomorrow.getTime() + 4 * 24 * 60 * 60 * 1000),
        nights: 4,
        guests: 2,
        totalAmount: 1260000.0,
        status: ReservationStatus.CONFIRMED,
        channel: BookingChannel.DIRECT,
        notes: 'Weekend getaway reservation',
        roomId: rooms[6]?.id || rooms[0].id,
        guestId: guests[6]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // Historical - Checked out last week
      {
        guestName: 'Diego Vargas',
        guestEmail: 'diego.vargas@email.com',
        guestPhone: '+57 307 345 6789',
        checkInDate: oneWeekAgo,
        checkOutDate: new Date(oneWeekAgo.getTime() + 3 * 24 * 60 * 60 * 1000),
        nights: 3,
        guests: 2,
        totalAmount: 945000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.BOOKING_COM,
        notes: 'Business trip',
        roomId: rooms[7]?.id || rooms[0].id,
        guestId: guests[7]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Carolina Pérez',
        guestEmail: 'carolina.perez@email.com',
        guestPhone: '+57 308 456 7890',
        checkInDate: oneWeekAgo,
        checkOutDate: new Date(oneWeekAgo.getTime() + 2 * 24 * 60 * 60 * 1000),
        nights: 2,
        guests: 1,
        totalAmount: 630000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.EXPEDIA,
        notes: 'Leisure travel',
        roomId: rooms[8]?.id || rooms[0].id,
        guestId: guests[8]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // Historical - Two weeks ago
      {
        guestName: 'Fernando Gómez',
        guestEmail: 'fernando.gomez@email.com',
        guestPhone: '+57 309 567 8901',
        checkInDate: twoWeeksAgo,
        checkOutDate: new Date(twoWeeksAgo.getTime() + 4 * 24 * 60 * 60 * 1000),
        nights: 4,
        guests: 3,
        totalAmount: 2520000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.AIRBNB,
        notes: 'Family vacation',
        roomId: rooms[9]?.id || rooms[0].id,
        guestId: guests[9]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Sofía Ramírez',
        guestEmail: 'sofia.ramirez@email.com',
        guestPhone: '+57 310 678 9012',
        checkInDate: twoWeeksAgo,
        checkOutDate: new Date(twoWeeksAgo.getTime() + 1 * 24 * 60 * 60 * 1000),
        nights: 1,
        guests: 1,
        totalAmount: 315000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.DIRECT,
        notes: 'One night stay',
        roomId: rooms[10]?.id || rooms[0].id,
        guestId: guests[0].id,
        userId: customerUser?.id,
      },

      // Historical - One month ago
      {
        guestName: 'Andrés Castro',
        guestEmail: 'andres.castro@email.com',
        guestPhone: '+57 311 789 0123',
        checkInDate: oneMonthAgo,
        checkOutDate: new Date(oneMonthAgo.getTime() + 5 * 24 * 60 * 60 * 1000),
        nights: 5,
        guests: 2,
        totalAmount: 3150000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.BOOKING_COM,
        notes: 'Extended business stay',
        roomId: rooms[11]?.id || rooms[0].id,
        guestId: guests[1]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Patricia Morales',
        guestEmail: 'patricia.morales@email.com',
        guestPhone: '+57 312 890 1234',
        checkInDate: oneMonthAgo,
        checkOutDate: new Date(oneMonthAgo.getTime() + 3 * 24 * 60 * 60 * 1000),
        nights: 3,
        guests: 1,
        totalAmount: 945000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.EXPEDIA,
        notes: 'Conference attendee',
        roomId: rooms[12]?.id || rooms[0].id,
        guestId: guests[2]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Ricardo Torres',
        guestEmail: 'ricardo.torres@email.com',
        guestPhone: '+57 313 901 2345',
        checkInDate: oneMonthAgo,
        checkOutDate: new Date(oneMonthAgo.getTime() + 2 * 24 * 60 * 60 * 1000),
        nights: 2,
        guests: 2,
        totalAmount: 630000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.DIRECT,
        notes: 'Couple getaway',
        roomId: rooms[13]?.id || rooms[0].id,
        guestId: guests[3]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // Historical - Two months ago
      {
        guestName: 'Valentina Ríos',
        guestEmail: 'valentina.rios@email.com',
        guestPhone: '+57 314 012 3456',
        checkInDate: twoMonthsAgo,
        checkOutDate: new Date(
          twoMonthsAgo.getTime() + 6 * 24 * 60 * 60 * 1000,
        ),
        nights: 6,
        guests: 4,
        totalAmount: 3780000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.AIRBNB,
        notes: 'Extended family stay',
        roomId: rooms[14]?.id || rooms[0].id,
        guestId: guests[4]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Miguel Ángel Díaz',
        guestEmail: 'miguel.diaz@email.com',
        guestPhone: '+57 315 123 4567',
        checkInDate: twoMonthsAgo,
        checkOutDate: new Date(
          twoMonthsAgo.getTime() + 3 * 24 * 60 * 60 * 1000,
        ),
        nights: 3,
        guests: 1,
        totalAmount: 945000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.BOOKING_COM,
        notes: 'Solo business trip',
        roomId: rooms[15]?.id || rooms[0].id,
        guestId: guests[5]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Laura Mendoza',
        guestEmail: 'laura.mendoza@email.com',
        guestPhone: '+57 316 234 5678',
        checkInDate: twoMonthsAgo,
        checkOutDate: new Date(
          twoMonthsAgo.getTime() + 2 * 24 * 60 * 60 * 1000,
        ),
        nights: 2,
        guests: 2,
        totalAmount: 630000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.EXPEDIA,
        notes: 'Anniversary trip',
        roomId: rooms[16]?.id || rooms[0].id,
        guestId: guests[6]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // Historical - Three months ago
      {
        guestName: 'Jorge Hernández',
        guestEmail: 'jorge.hernandez@email.com',
        guestPhone: '+57 317 345 6789',
        checkInDate: threeMonthsAgo,
        checkOutDate: new Date(
          threeMonthsAgo.getTime() + 4 * 24 * 60 * 60 * 1000,
        ),
        nights: 4,
        guests: 3,
        totalAmount: 2520000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.DIRECT,
        notes: 'Family reunion',
        roomId: rooms[17]?.id || rooms[0].id,
        guestId: guests[7]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Camila Ortiz',
        guestEmail: 'camila.ortiz@email.com',
        guestPhone: '+57 318 456 7890',
        checkInDate: threeMonthsAgo,
        checkOutDate: new Date(
          threeMonthsAgo.getTime() + 5 * 24 * 60 * 60 * 1000,
        ),
        nights: 5,
        guests: 2,
        totalAmount: 1575000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.BOOKING_COM,
        notes: 'Honeymoon',
        roomId: rooms[18]?.id || rooms[0].id,
        guestId: guests[8]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Esteban Ruiz',
        guestEmail: 'esteban.ruiz@email.com',
        guestPhone: '+57 319 567 8901',
        checkInDate: threeMonthsAgo,
        checkOutDate: new Date(
          threeMonthsAgo.getTime() + 1 * 24 * 60 * 60 * 1000,
        ),
        nights: 1,
        guests: 1,
        totalAmount: 315000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.AIRBNB,
        notes: 'Quick business stop',
        roomId: rooms[19]?.id || rooms[0].id,
        guestId: guests[9]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // === 2025 Historical Reservations (January to current month) ===
      // January 2025
      {
        guestName: 'Daniela Ortega',
        guestEmail: 'daniela.ortega2025@email.com',
        guestPhone: '+57 326 111 1111',
        checkInDate: createDate(2025, 1, 8),
        checkOutDate: createDate(2025, 1, 11),
        nights: 3,
        guests: 2,
        totalAmount: 945000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.DIRECT,
        notes: 'New Year celebration 2025',
        roomId: rooms[0]?.id || rooms[0].id,
        guestId: guests[0]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Eduardo Salinas',
        guestEmail: 'eduardo.salinas2025@email.com',
        guestPhone: '+57 326 111 2222',
        checkInDate: createDate(2025, 1, 22),
        checkOutDate: createDate(2025, 1, 25),
        nights: 3,
        guests: 1,
        totalAmount: 945000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.BOOKING_COM,
        notes: 'Business trip 2025',
        roomId: rooms[1]?.id || rooms[0].id,
        guestId: guests[1]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // February 2025
      {
        guestName: 'Fernanda Campos',
        guestEmail: 'fernanda.campos2025@email.com',
        guestPhone: '+57 326 222 1111',
        checkInDate: createDate(2025, 2, 12),
        checkOutDate: createDate(2025, 2, 15),
        nights: 3,
        guests: 2,
        totalAmount: 945000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.EXPEDIA,
        notes: 'Valentine 2025',
        roomId: rooms[2]?.id || rooms[0].id,
        guestId: guests[2]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Gustavo Robles',
        guestEmail: 'gustavo.robles2025@email.com',
        guestPhone: '+57 326 222 2222',
        checkInDate: createDate(2025, 2, 24),
        checkOutDate: createDate(2025, 2, 26),
        nights: 2,
        guests: 1,
        totalAmount: 630000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.AIRBNB,
        notes: 'Weekend getaway 2025',
        roomId: rooms[3]?.id || rooms[0].id,
        guestId: guests[3]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // March 2025
      {
        guestName: 'Helena Vega',
        guestEmail: 'helena.vega2025@email.com',
        guestPhone: '+57 326 333 1111',
        checkInDate: createDate(2025, 3, 10),
        checkOutDate: createDate(2025, 3, 14),
        nights: 4,
        guests: 3,
        totalAmount: 2520000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.DIRECT,
        notes: 'Spring vacation 2025',
        roomId: rooms[4]?.id || rooms[0].id,
        guestId: guests[4]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Ignacio Bravo',
        guestEmail: 'ignacio.bravo2025@email.com',
        guestPhone: '+57 326 333 2222',
        checkInDate: createDate(2025, 3, 25),
        checkOutDate: createDate(2025, 3, 28),
        nights: 3,
        guests: 2,
        totalAmount: 1890000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.BOOKING_COM,
        notes: 'Easter 2025',
        roomId: rooms[5]?.id || rooms[0].id,
        guestId: guests[5]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // April 2025
      {
        guestName: 'Julia Santana',
        guestEmail: 'julia.santana2025@email.com',
        guestPhone: '+57 326 444 1111',
        checkInDate: createDate(2025, 4, 8),
        checkOutDate: createDate(2025, 4, 12),
        nights: 4,
        guests: 2,
        totalAmount: 1260000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.EXPEDIA,
        notes: 'Spring break 2025',
        roomId: rooms[6]?.id || rooms[0].id,
        guestId: guests[6]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Kevin Montes',
        guestEmail: 'kevin.montes2025@email.com',
        guestPhone: '+57 326 444 2222',
        checkInDate: createDate(2025, 4, 22),
        checkOutDate: createDate(2025, 4, 25),
        nights: 3,
        guests: 1,
        totalAmount: 945000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.AIRBNB,
        notes: 'Solo adventure 2025',
        roomId: rooms[7]?.id || rooms[0].id,
        guestId: guests[7]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // May 2025
      {
        guestName: 'Lorena Figueroa',
        guestEmail: 'lorena.figueroa2025@email.com',
        guestPhone: '+57 326 555 1111',
        checkInDate: createDate(2025, 5, 10),
        checkOutDate: createDate(2025, 5, 15),
        nights: 5,
        guests: 2,
        totalAmount: 3150000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.DIRECT,
        notes: 'Anniversary 2025',
        roomId: rooms[8]?.id || rooms[0].id,
        guestId: guests[8]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Manuel Cardenas',
        guestEmail: 'manuel.cardenas2025@email.com',
        guestPhone: '+57 326 555 2222',
        checkInDate: createDate(2025, 5, 26),
        checkOutDate: createDate(2025, 5, 28),
        nights: 2,
        guests: 1,
        totalAmount: 630000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.BOOKING_COM,
        notes: 'Business trip 2025',
        roomId: rooms[9]?.id || rooms[0].id,
        guestId: guests[9]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // June 2025
      {
        guestName: 'Natalia Herrera',
        guestEmail: 'natalia.herrera2025@email.com',
        guestPhone: '+57 326 666 1111',
        checkInDate: createDate(2025, 6, 9),
        checkOutDate: createDate(2025, 6, 13),
        nights: 4,
        guests: 3,
        totalAmount: 2520000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.EXPEDIA,
        notes: 'Summer start 2025',
        roomId: rooms[0]?.id || rooms[0].id,
        guestId: guests[0]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Óscar Villegas',
        guestEmail: 'oscar.villegas2025@email.com',
        guestPhone: '+57 326 666 2222',
        checkInDate: createDate(2025, 6, 24),
        checkOutDate: createDate(2025, 6, 28),
        nights: 4,
        guests: 2,
        totalAmount: 2520000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.AIRBNB,
        notes: 'Mid-year vacation 2025',
        roomId: rooms[1]?.id || rooms[0].id,
        guestId: guests[1]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // July 2025
      {
        guestName: 'Paola Bermúdez',
        guestEmail: 'paola.bermudez2025@email.com',
        guestPhone: '+57 326 777 1111',
        checkInDate: createDate(2025, 7, 8),
        checkOutDate: createDate(2025, 7, 13),
        nights: 5,
        guests: 4,
        totalAmount: 3150000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.DIRECT,
        notes: 'Family summer 2025',
        roomId: rooms[2]?.id || rooms[0].id,
        guestId: guests[2]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Quintín Acosta',
        guestEmail: 'quintin.acosta2025@email.com',
        guestPhone: '+57 326 777 2222',
        checkInDate: createDate(2025, 7, 22),
        checkOutDate: createDate(2025, 7, 26),
        nights: 4,
        guests: 2,
        totalAmount: 1260000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.BOOKING_COM,
        notes: 'Summer holiday 2025',
        roomId: rooms[3]?.id || rooms[0].id,
        guestId: guests[3]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // August 2025
      {
        guestName: 'Rosa Maldonado',
        guestEmail: 'rosa.maldonado2025@email.com',
        guestPhone: '+57 326 888 1111',
        checkInDate: createDate(2025, 8, 5),
        checkOutDate: createDate(2025, 8, 10),
        nights: 5,
        guests: 3,
        totalAmount: 3150000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.EXPEDIA,
        notes: 'Extended summer 2025',
        roomId: rooms[4]?.id || rooms[0].id,
        guestId: guests[4]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Sergio Luna',
        guestEmail: 'sergio.luna2025@email.com',
        guestPhone: '+57 326 888 2222',
        checkInDate: createDate(2025, 8, 24),
        checkOutDate: createDate(2025, 8, 27),
        nights: 3,
        guests: 1,
        totalAmount: 945000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.AIRBNB,
        notes: 'Late summer 2025',
        roomId: rooms[5]?.id || rooms[0].id,
        guestId: guests[5]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // September 2025
      {
        guestName: 'Teresa Palacios',
        guestEmail: 'teresa.palacios2025@email.com',
        guestPhone: '+57 326 999 1111',
        checkInDate: createDate(2025, 9, 10),
        checkOutDate: createDate(2025, 9, 13),
        nights: 3,
        guests: 2,
        totalAmount: 945000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.DIRECT,
        notes: 'September break 2025',
        roomId: rooms[6]?.id || rooms[0].id,
        guestId: guests[6]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Ulises Castro',
        guestEmail: 'ulises.castro2025@email.com',
        guestPhone: '+57 326 999 2222',
        checkInDate: createDate(2025, 9, 26),
        checkOutDate: createDate(2025, 9, 29),
        nights: 3,
        guests: 1,
        totalAmount: 945000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.BOOKING_COM,
        notes: 'Business trip 2025',
        roomId: rooms[7]?.id || rooms[0].id,
        guestId: guests[7]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // October 2025 (current month - mix of checked out and current)
      {
        guestName: 'Verónica Solis',
        guestEmail: 'veronica.solis2025@email.com',
        guestPhone: '+57 327 000 1111',
        checkInDate: createDate(2025, 10, 5),
        checkOutDate: createDate(2025, 10, 9),
        nights: 4,
        guests: 2,
        totalAmount: 1260000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.EXPEDIA,
        notes: 'October holiday 2025',
        roomId: rooms[8]?.id || rooms[0].id,
        guestId: guests[8]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // Some cancelled reservations
      {
        guestName: 'Natalia Suárez',
        guestEmail: 'natalia.suarez@email.com',
        guestPhone: '+57 320 678 9012',
        checkInDate: oneMonthAgo,
        checkOutDate: new Date(oneMonthAgo.getTime() + 2 * 24 * 60 * 60 * 1000),
        nights: 2,
        guests: 2,
        totalAmount: 630000.0,
        status: ReservationStatus.CANCELLED,
        channel: BookingChannel.BOOKING_COM,
        notes: 'Cancelled due to emergency',
        roomId: rooms[5]?.id || rooms[0].id,
        guestId: guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Gabriel Reyes',
        guestEmail: 'gabriel.reyes@email.com',
        guestPhone: '+57 321 789 0123',
        checkInDate: twoWeeksAgo,
        checkOutDate: new Date(twoWeeksAgo.getTime() + 3 * 24 * 60 * 60 * 1000),
        nights: 3,
        guests: 1,
        totalAmount: 945000.0,
        status: ReservationStatus.CANCELLED,
        channel: BookingChannel.DIRECT,
        notes: 'Plans changed',
        roomId: rooms[6]?.id || rooms[0].id,
        guestId: guests[1]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // === 2024 Historical Reservations (all months) ===
      // January 2024
      {
        guestName: 'Carlos Mendoza',
        guestEmail: 'carlos.mendoza2024@email.com',
        guestPhone: '+57 322 111 1111',
        checkInDate: createDate(2024, 1, 5),
        checkOutDate: createDate(2024, 1, 8),
        nights: 3,
        guests: 2,
        totalAmount: 945000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.BOOKING_COM,
        notes: 'Año nuevo - vacation',
        roomId: rooms[0]?.id || rooms[0].id,
        guestId: guests[0]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Ana Beltrán',
        guestEmail: 'ana.beltran2024@email.com',
        guestPhone: '+57 322 111 2222',
        checkInDate: createDate(2024, 1, 15),
        checkOutDate: createDate(2024, 1, 18),
        nights: 3,
        guests: 1,
        totalAmount: 945000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.EXPEDIA,
        notes: 'Business trip',
        roomId: rooms[1]?.id || rooms[0].id,
        guestId: guests[1]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Roberto Quintero',
        guestEmail: 'roberto.quintero2024@email.com',
        guestPhone: '+57 322 111 3333',
        checkInDate: createDate(2024, 1, 25),
        checkOutDate: createDate(2024, 1, 27),
        nights: 2,
        guests: 2,
        totalAmount: 630000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.DIRECT,
        notes: 'Weekend getaway',
        roomId: rooms[2]?.id || rooms[0].id,
        guestId: guests[2]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // February 2024
      {
        guestName: 'María Ángeles',
        guestEmail: 'maria.angeles2024@email.com',
        guestPhone: '+57 322 222 1111',
        checkInDate: createDate(2024, 2, 10),
        checkOutDate: createDate(2024, 2, 14),
        nights: 4,
        guests: 2,
        totalAmount: 2520000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.AIRBNB,
        notes: 'Valentine celebration',
        roomId: rooms[3]?.id || rooms[0].id,
        guestId: guests[3]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'José Ramírez',
        guestEmail: 'jose.ramirez2024@email.com',
        guestPhone: '+57 322 222 2222',
        checkInDate: createDate(2024, 2, 20),
        checkOutDate: createDate(2024, 2, 22),
        nights: 2,
        guests: 1,
        totalAmount: 630000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.BOOKING_COM,
        notes: 'Business conference',
        roomId: rooms[4]?.id || rooms[0].id,
        guestId: guests[4]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // March 2024
      {
        guestName: 'Sandra Pinto',
        guestEmail: 'sandra.pinto2024@email.com',
        guestPhone: '+57 322 333 1111',
        checkInDate: createDate(2024, 3, 8),
        checkOutDate: createDate(2024, 3, 12),
        nights: 4,
        guests: 3,
        totalAmount: 2520000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.EXPEDIA,
        notes: 'Family vacation',
        roomId: rooms[5]?.id || rooms[0].id,
        guestId: guests[5]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Luis Arias',
        guestEmail: 'luis.arias2024@email.com',
        guestPhone: '+57 322 333 2222',
        checkInDate: createDate(2024, 3, 22),
        checkOutDate: createDate(2024, 3, 25),
        nights: 3,
        guests: 2,
        totalAmount: 1890000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.DIRECT,
        notes: 'Spring break',
        roomId: rooms[6]?.id || rooms[0].id,
        guestId: guests[6]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // April 2024
      {
        guestName: 'Diana Salazar',
        guestEmail: 'diana.salazar2024@email.com',
        guestPhone: '+57 322 444 1111',
        checkInDate: createDate(2024, 4, 5),
        checkOutDate: createDate(2024, 4, 9),
        nights: 4,
        guests: 2,
        totalAmount: 1260000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.BOOKING_COM,
        notes: 'Easter vacation',
        roomId: rooms[7]?.id || rooms[0].id,
        guestId: guests[7]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Héctor Muñoz',
        guestEmail: 'hector.munoz2024@email.com',
        guestPhone: '+57 322 444 2222',
        checkInDate: createDate(2024, 4, 18),
        checkOutDate: createDate(2024, 4, 21),
        nights: 3,
        guests: 1,
        totalAmount: 945000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.AIRBNB,
        notes: 'Solo travel',
        roomId: rooms[8]?.id || rooms[0].id,
        guestId: guests[8]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // May 2024
      {
        guestName: 'Paula Cortés',
        guestEmail: 'paula.cortes2024@email.com',
        guestPhone: '+57 322 555 1111',
        checkInDate: createDate(2024, 5, 10),
        checkOutDate: createDate(2024, 5, 15),
        nights: 5,
        guests: 2,
        totalAmount: 3150000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.EXPEDIA,
        notes: 'Anniversary trip',
        roomId: rooms[9]?.id || rooms[0].id,
        guestId: guests[9]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Germán Soto',
        guestEmail: 'german.soto2024@email.com',
        guestPhone: '+57 322 555 2222',
        checkInDate: createDate(2024, 5, 24),
        checkOutDate: createDate(2024, 5, 26),
        nights: 2,
        guests: 1,
        totalAmount: 630000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.DIRECT,
        notes: 'Quick business trip',
        roomId: rooms[10]?.id || rooms[0].id,
        guestId: guests[0]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // June 2024
      {
        guestName: 'Claudia Rojas',
        guestEmail: 'claudia.rojas2024@email.com',
        guestPhone: '+57 322 666 1111',
        checkInDate: createDate(2024, 6, 7),
        checkOutDate: createDate(2024, 6, 11),
        nights: 4,
        guests: 3,
        totalAmount: 2520000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.BOOKING_COM,
        notes: 'Summer vacation start',
        roomId: rooms[11]?.id || rooms[0].id,
        guestId: guests[1]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Alberto Vega',
        guestEmail: 'alberto.vega2024@email.com',
        guestPhone: '+57 322 666 2222',
        checkInDate: createDate(2024, 6, 20),
        checkOutDate: createDate(2024, 6, 24),
        nights: 4,
        guests: 2,
        totalAmount: 2520000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.AIRBNB,
        notes: 'Mid-year getaway',
        roomId: rooms[12]?.id || rooms[0].id,
        guestId: guests[2]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // July 2024
      {
        guestName: 'Beatriz Luna',
        guestEmail: 'beatriz.luna2024@email.com',
        guestPhone: '+57 322 777 1111',
        checkInDate: createDate(2024, 7, 5),
        checkOutDate: createDate(2024, 7, 10),
        nights: 5,
        guests: 4,
        totalAmount: 3150000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.EXPEDIA,
        notes: 'Summer family vacation',
        roomId: rooms[13]?.id || rooms[0].id,
        guestId: guests[3]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Felipe Navarro',
        guestEmail: 'felipe.navarro2024@email.com',
        guestPhone: '+57 322 777 2222',
        checkInDate: createDate(2024, 7, 18),
        checkOutDate: createDate(2024, 7, 22),
        nights: 4,
        guests: 2,
        totalAmount: 1260000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.DIRECT,
        notes: 'Summer break',
        roomId: rooms[14]?.id || rooms[0].id,
        guestId: guests[4]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // August 2024
      {
        guestName: 'Gloria Medina',
        guestEmail: 'gloria.medina2024@email.com',
        guestPhone: '+57 322 888 1111',
        checkInDate: createDate(2024, 8, 2),
        checkOutDate: createDate(2024, 8, 7),
        nights: 5,
        guests: 3,
        totalAmount: 3150000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.BOOKING_COM,
        notes: 'Extended vacation',
        roomId: rooms[15]?.id || rooms[0].id,
        guestId: guests[5]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Iván Paredes',
        guestEmail: 'ivan.paredes2024@email.com',
        guestPhone: '+57 322 888 2222',
        checkInDate: createDate(2024, 8, 20),
        checkOutDate: createDate(2024, 8, 23),
        nights: 3,
        guests: 1,
        totalAmount: 945000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.AIRBNB,
        notes: 'Late summer trip',
        roomId: rooms[16]?.id || rooms[0].id,
        guestId: guests[6]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // September 2024
      {
        guestName: 'Juliana Cruz',
        guestEmail: 'juliana.cruz2024@email.com',
        guestPhone: '+57 322 999 1111',
        checkInDate: createDate(2024, 9, 6),
        checkOutDate: createDate(2024, 9, 9),
        nights: 3,
        guests: 2,
        totalAmount: 945000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.EXPEDIA,
        notes: 'Back to school break',
        roomId: rooms[17]?.id || rooms[0].id,
        guestId: guests[7]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Mauricio Rivas',
        guestEmail: 'mauricio.rivas2024@email.com',
        guestPhone: '+57 322 999 2222',
        checkInDate: createDate(2024, 9, 22),
        checkOutDate: createDate(2024, 9, 25),
        nights: 3,
        guests: 1,
        totalAmount: 945000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.DIRECT,
        notes: 'Business meeting',
        roomId: rooms[18]?.id || rooms[0].id,
        guestId: guests[8]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // October 2024
      {
        guestName: 'Nora Campos',
        guestEmail: 'nora.campos2024@email.com',
        guestPhone: '+57 323 000 1111',
        checkInDate: createDate(2024, 10, 10),
        checkOutDate: createDate(2024, 10, 14),
        nights: 4,
        guests: 2,
        totalAmount: 1260000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.BOOKING_COM,
        notes: 'Columbus Day weekend',
        roomId: rooms[19]?.id || rooms[0].id,
        guestId: guests[9]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Oscar Fuentes',
        guestEmail: 'oscar.fuentes2024@email.com',
        guestPhone: '+57 323 000 2222',
        checkInDate: createDate(2024, 10, 25),
        checkOutDate: createDate(2024, 10, 28),
        nights: 3,
        guests: 3,
        totalAmount: 1890000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.AIRBNB,
        notes: 'Halloween trip',
        roomId: rooms[0]?.id || rooms[0].id,
        guestId: guests[0]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // November 2024
      {
        guestName: 'Patricia Duarte',
        guestEmail: 'patricia.duarte2024@email.com',
        guestPhone: '+57 323 111 1111',
        checkInDate: createDate(2024, 11, 8),
        checkOutDate: createDate(2024, 11, 12),
        nights: 4,
        guests: 2,
        totalAmount: 2520000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.EXPEDIA,
        notes: 'November holiday',
        roomId: rooms[1]?.id || rooms[0].id,
        guestId: guests[1]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Rodrigo Peña',
        guestEmail: 'rodrigo.pena2024@email.com',
        guestPhone: '+57 323 111 2222',
        checkInDate: createDate(2024, 11, 22),
        checkOutDate: createDate(2024, 11, 25),
        nights: 3,
        guests: 1,
        totalAmount: 945000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.DIRECT,
        notes: 'Pre-holiday travel',
        roomId: rooms[2]?.id || rooms[0].id,
        guestId: guests[2]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // December 2024
      {
        guestName: 'Silvia Mejía',
        guestEmail: 'silvia.mejia2024@email.com',
        guestPhone: '+57 323 222 1111',
        checkInDate: createDate(2024, 12, 15),
        checkOutDate: createDate(2024, 12, 20),
        nights: 5,
        guests: 4,
        totalAmount: 3150000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.BOOKING_COM,
        notes: 'Christmas vacation',
        roomId: rooms[3]?.id || rooms[0].id,
        guestId: guests[3]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Tomás Ortega',
        guestEmail: 'tomas.ortega2024@email.com',
        guestPhone: '+57 323 222 2222',
        checkInDate: createDate(2024, 12, 28),
        checkOutDate: createDate(2024, 12, 31),
        nights: 3,
        guests: 2,
        totalAmount: 1890000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.AIRBNB,
        notes: 'New Year celebration',
        roomId: rooms[4]?.id || rooms[0].id,
        guestId: guests[4]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // === 2023 Historical Reservations (all months) ===
      // January 2023
      {
        guestName: 'Adriana Castro',
        guestEmail: 'adriana.castro2023@email.com',
        guestPhone: '+57 324 111 1111',
        checkInDate: createDate(2023, 1, 7),
        checkOutDate: createDate(2023, 1, 10),
        nights: 3,
        guests: 2,
        totalAmount: 945000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.DIRECT,
        notes: 'New Year vacation 2023',
        roomId: rooms[5]?.id || rooms[0].id,
        guestId: guests[5]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Bruno Vargas',
        guestEmail: 'bruno.vargas2023@email.com',
        guestPhone: '+57 324 111 2222',
        checkInDate: createDate(2023, 1, 20),
        checkOutDate: createDate(2023, 1, 23),
        nights: 3,
        guests: 1,
        totalAmount: 945000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.BOOKING_COM,
        notes: 'Business trip 2023',
        roomId: rooms[6]?.id || rooms[0].id,
        guestId: guests[6]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // February 2023
      {
        guestName: 'Carolina Flores',
        guestEmail: 'carolina.flores2023@email.com',
        guestPhone: '+57 324 222 1111',
        checkInDate: createDate(2023, 2, 12),
        checkOutDate: createDate(2023, 2, 15),
        nights: 3,
        guests: 2,
        totalAmount: 945000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.EXPEDIA,
        notes: 'Valentine 2023',
        roomId: rooms[7]?.id || rooms[0].id,
        guestId: guests[7]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'David Montes',
        guestEmail: 'david.montes2023@email.com',
        guestPhone: '+57 324 222 2222',
        checkInDate: createDate(2023, 2, 25),
        checkOutDate: createDate(2023, 2, 27),
        nights: 2,
        guests: 1,
        totalAmount: 630000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.AIRBNB,
        notes: 'Weekend stay 2023',
        roomId: rooms[8]?.id || rooms[0].id,
        guestId: guests[8]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // March 2023
      {
        guestName: 'Elena Sandoval',
        guestEmail: 'elena.sandoval2023@email.com',
        guestPhone: '+57 324 333 1111',
        checkInDate: createDate(2023, 3, 10),
        checkOutDate: createDate(2023, 3, 14),
        nights: 4,
        guests: 3,
        totalAmount: 2520000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.DIRECT,
        notes: 'Spring break 2023',
        roomId: rooms[9]?.id || rooms[0].id,
        guestId: guests[9]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Francisco León',
        guestEmail: 'francisco.leon2023@email.com',
        guestPhone: '+57 324 333 2222',
        checkInDate: createDate(2023, 3, 24),
        checkOutDate: createDate(2023, 3, 27),
        nights: 3,
        guests: 2,
        totalAmount: 1890000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.BOOKING_COM,
        notes: 'Easter 2023',
        roomId: rooms[10]?.id || rooms[0].id,
        guestId: guests[0]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // April 2023
      {
        guestName: 'Gabriela Suárez',
        guestEmail: 'gabriela.suarez2023@email.com',
        guestPhone: '+57 324 444 1111',
        checkInDate: createDate(2023, 4, 8),
        checkOutDate: createDate(2023, 4, 12),
        nights: 4,
        guests: 2,
        totalAmount: 1260000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.EXPEDIA,
        notes: 'April vacation 2023',
        roomId: rooms[11]?.id || rooms[0].id,
        guestId: guests[1]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Hugo Gallego',
        guestEmail: 'hugo.gallego2023@email.com',
        guestPhone: '+57 324 444 2222',
        checkInDate: createDate(2023, 4, 22),
        checkOutDate: createDate(2023, 4, 25),
        nights: 3,
        guests: 1,
        totalAmount: 945000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.AIRBNB,
        notes: 'Solo travel 2023',
        roomId: rooms[12]?.id || rooms[0].id,
        guestId: guests[2]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // May 2023
      {
        guestName: 'Inés Prieto',
        guestEmail: 'ines.prieto2023@email.com',
        guestPhone: '+57 324 555 1111',
        checkInDate: createDate(2023, 5, 12),
        checkOutDate: createDate(2023, 5, 17),
        nights: 5,
        guests: 2,
        totalAmount: 3150000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.DIRECT,
        notes: 'May vacation 2023',
        roomId: rooms[13]?.id || rooms[0].id,
        guestId: guests[3]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Javier Parra',
        guestEmail: 'javier.parra2023@email.com',
        guestPhone: '+57 324 555 2222',
        checkInDate: createDate(2023, 5, 26),
        checkOutDate: createDate(2023, 5, 28),
        nights: 2,
        guests: 1,
        totalAmount: 630000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.BOOKING_COM,
        notes: 'Quick trip 2023',
        roomId: rooms[14]?.id || rooms[0].id,
        guestId: guests[4]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // June 2023
      {
        guestName: 'Karina Blanco',
        guestEmail: 'karina.blanco2023@email.com',
        guestPhone: '+57 324 666 1111',
        checkInDate: createDate(2023, 6, 9),
        checkOutDate: createDate(2023, 6, 13),
        nights: 4,
        guests: 3,
        totalAmount: 2520000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.EXPEDIA,
        notes: 'Summer start 2023',
        roomId: rooms[15]?.id || rooms[0].id,
        guestId: guests[5]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Leonardo Cano',
        guestEmail: 'leonardo.cano2023@email.com',
        guestPhone: '+57 324 666 2222',
        checkInDate: createDate(2023, 6, 23),
        checkOutDate: createDate(2023, 6, 27),
        nights: 4,
        guests: 2,
        totalAmount: 2520000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.AIRBNB,
        notes: 'Mid-year 2023',
        roomId: rooms[16]?.id || rooms[0].id,
        guestId: guests[6]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // July 2023
      {
        guestName: 'Mariana Reyes',
        guestEmail: 'mariana.reyes2023@email.com',
        guestPhone: '+57 324 777 1111',
        checkInDate: createDate(2023, 7, 7),
        checkOutDate: createDate(2023, 7, 12),
        nights: 5,
        guests: 4,
        totalAmount: 3150000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.DIRECT,
        notes: 'Family summer 2023',
        roomId: rooms[17]?.id || rooms[0].id,
        guestId: guests[7]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Nicolás Aguilar',
        guestEmail: 'nicolas.aguilar2023@email.com',
        guestPhone: '+57 324 777 2222',
        checkInDate: createDate(2023, 7, 20),
        checkOutDate: createDate(2023, 7, 24),
        nights: 4,
        guests: 2,
        totalAmount: 1260000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.BOOKING_COM,
        notes: 'July vacation 2023',
        roomId: rooms[18]?.id || rooms[0].id,
        guestId: guests[8]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // August 2023
      {
        guestName: 'Olga Serrano',
        guestEmail: 'olga.serrano2023@email.com',
        guestPhone: '+57 324 888 1111',
        checkInDate: createDate(2023, 8, 4),
        checkOutDate: createDate(2023, 8, 9),
        nights: 5,
        guests: 3,
        totalAmount: 3150000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.EXPEDIA,
        notes: 'Extended summer 2023',
        roomId: rooms[19]?.id || rooms[0].id,
        guestId: guests[9]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Pablo Rincón',
        guestEmail: 'pablo.rincon2023@email.com',
        guestPhone: '+57 324 888 2222',
        checkInDate: createDate(2023, 8, 22),
        checkOutDate: createDate(2023, 8, 25),
        nights: 3,
        guests: 1,
        totalAmount: 945000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.AIRBNB,
        notes: 'Late summer 2023',
        roomId: rooms[0]?.id || rooms[0].id,
        guestId: guests[0]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // September 2023
      {
        guestName: 'Quetzali Mora',
        guestEmail: 'quetzali.mora2023@email.com',
        guestPhone: '+57 324 999 1111',
        checkInDate: createDate(2023, 9, 8),
        checkOutDate: createDate(2023, 9, 11),
        nights: 3,
        guests: 2,
        totalAmount: 945000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.DIRECT,
        notes: 'September getaway 2023',
        roomId: rooms[1]?.id || rooms[0].id,
        guestId: guests[1]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Ramiro Villegas',
        guestEmail: 'ramiro.villegas2023@email.com',
        guestPhone: '+57 324 999 2222',
        checkInDate: createDate(2023, 9, 24),
        checkOutDate: createDate(2023, 9, 27),
        nights: 3,
        guests: 1,
        totalAmount: 945000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.BOOKING_COM,
        notes: 'Business 2023',
        roomId: rooms[2]?.id || rooms[0].id,
        guestId: guests[2]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // October 2023
      {
        guestName: 'Sara Escobar',
        guestEmail: 'sara.escobar2023@email.com',
        guestPhone: '+57 325 000 1111',
        checkInDate: createDate(2023, 10, 12),
        checkOutDate: createDate(2023, 10, 16),
        nights: 4,
        guests: 2,
        totalAmount: 1260000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.EXPEDIA,
        notes: 'October holiday 2023',
        roomId: rooms[3]?.id || rooms[0].id,
        guestId: guests[3]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Tadeo Ibáñez',
        guestEmail: 'tadeo.ibanez2023@email.com',
        guestPhone: '+57 325 000 2222',
        checkInDate: createDate(2023, 10, 27),
        checkOutDate: createDate(2023, 10, 30),
        nights: 3,
        guests: 3,
        totalAmount: 1890000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.AIRBNB,
        notes: 'Halloween 2023',
        roomId: rooms[4]?.id || rooms[0].id,
        guestId: guests[4]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // November 2023
      {
        guestName: 'Úrsula Bravo',
        guestEmail: 'ursula.bravo2023@email.com',
        guestPhone: '+57 325 111 1111',
        checkInDate: createDate(2023, 11, 10),
        checkOutDate: createDate(2023, 11, 14),
        nights: 4,
        guests: 2,
        totalAmount: 2520000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.DIRECT,
        notes: 'November 2023',
        roomId: rooms[5]?.id || rooms[0].id,
        guestId: guests[5]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Víctor Pinto',
        guestEmail: 'victor.pinto2023@email.com',
        guestPhone: '+57 325 111 2222',
        checkInDate: createDate(2023, 11, 24),
        checkOutDate: createDate(2023, 11, 27),
        nights: 3,
        guests: 1,
        totalAmount: 945000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.BOOKING_COM,
        notes: 'Thanksgiving 2023',
        roomId: rooms[6]?.id || rooms[0].id,
        guestId: guests[6]?.id || guests[0].id,
        userId: customerUser?.id,
      },

      // December 2023
      {
        guestName: 'Wendy Alvarado',
        guestEmail: 'wendy.alvarado2023@email.com',
        guestPhone: '+57 325 222 1111',
        checkInDate: createDate(2023, 12, 16),
        checkOutDate: createDate(2023, 12, 21),
        nights: 5,
        guests: 4,
        totalAmount: 3150000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.EXPEDIA,
        notes: 'Christmas 2023',
        roomId: rooms[7]?.id || rooms[0].id,
        guestId: guests[7]?.id || guests[0].id,
        userId: customerUser?.id,
      },
      {
        guestName: 'Xavier Zambrano',
        guestEmail: 'xavier.zambrano2023@email.com',
        guestPhone: '+57 325 222 2222',
        checkInDate: createDate(2023, 12, 29),
        checkOutDate: createDate(2023, 12, 31),
        nights: 2,
        guests: 2,
        totalAmount: 1260000.0,
        status: ReservationStatus.CHECKED_OUT,
        channel: BookingChannel.AIRBNB,
        notes: 'New Year 2023',
        roomId: rooms[8]?.id || rooms[0].id,
        guestId: guests[8]?.id || guests[0].id,
        userId: customerUser?.id,
      },
    ];

    for (const reservationData of reservations) {
      const existing = await this.reservationRepository.findOne({
        where: {
          guestEmail: reservationData.guestEmail,
          roomId: reservationData.roomId,
          checkInDate: reservationData.checkInDate,
        },
      });

      if (!existing) {
        await this.reservationRepository.save(reservationData);
      }
    }

    console.log(`✅ Seeded ${reservations.length} predefined reservations`);
  }
}
